/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

// Add this import to reference MainActivity correctly
import com.AfamObioha.kaminari_app.MainActivity;

public class AppTest {
    @Test
    public void testMainActivity() {
        MainActivity classUnderTest = new MainActivity();
        assertNotNull("MainActivity should be created successfully", classUnderTest);
    }
}
